import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import BuildCard from "~/components/BuildCard";
import BuildStyleSelect from "~/components/BuildStyleSelect";
import { buildStyles } from "~/pages/submit-build";
import { api } from "~/utils/api";

const FindBuildsPage: NextPage = () => {
  const [buildStyle, setBuildStyle] = useState(buildStyles[0]);

  const { query } = useRouter();
  const { opponentRace = "", raceName = "" } = query as {
    opponentRace: string;
    raceName: string;
  };
  const builds = api.builds.getBuildsByMatchUp.useQuery(
    {
      matchUp: `${raceName.toLowerCase().charAt(0)}v${opponentRace
        .toLowerCase()
        .charAt(0)}`,
    },
    {
      initialData: [],
    }
  );
  const filteredBuilds = builds.data.filter(
    (build) => build.style === buildStyle
  );

  return (
    <>
      <Head>
        <title>Match Up</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 px-4 py-12 ">
        <h1 className="text-4xl">
          {raceName} vs {opponentRace}
        </h1>
        <BuildStyleSelect setBuildStyle={setBuildStyle} />
        <section className="flex flex-wrap gap-4">
          {filteredBuilds.map((build) => (
            <BuildCard key={build.id} build={build} />
          ))}
        </section>
      </main>
    </>
  );
};

export default FindBuildsPage;
