import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const FindBuildsPage: NextPage = () => {
  const { raceName } = useRouter().query as { raceName: string };
  return (
    <>
      <Head>
        <title>Select Opponent Race</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 ">
        <section className="flex flex-col items-center gap-5">
          <p>{raceName}</p>
          <p>VS.</p>
          <p>(Select Opponent&apos;s Race)</p>
        </section>
        <ul className="grid grid-cols-3 gap-5">
          {/* <li>
            <RaceCard
              isOpponent
              href={`/races/${raceName}/match-ups/zerg`}
              raceImageSrc="/images/zerg.jpg"
              raceName="Zerg"
            />
          </li>
          <li>
            <RaceCard
              isOpponent
              href={`/races/${raceName}/match-ups/protoss`}
              raceImageSrc="/images/protoss.jpg"
              raceName="Protoss"
            />
          </li>
          <li>
            <RaceCard
              isOpponent
              href={`/races/${raceName}/match-ups/terran`}
              raceImageSrc="/images/terran.jpg"
              raceName="Terran"
            />
          </li> */}
        </ul>
      </main>
    </>
  );
};

export default FindBuildsPage;
