import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";

import { api } from "~/utils/api";

const SubmitBuildPage: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();

  const [build, setBuildOrder] = useState("");
  const [matchUp, setMatchUp] = useState("zvt");

  const router = useRouter();

  const handleSubmitBuildOrder = async (e: React.FormEvent) => {
    e.preventDefault();
    await createBuildMutation.mutateAsync({
      matchUp,
      build,
    });
    void router.push("/");
  };
  return (
    <>
      <Head>
        <title>Submit a Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 bg-gray-800 text-white">
        <h1>Submit a Build Order</h1>
        <form
          onSubmit={handleSubmitBuildOrder}
          className="flex flex-col gap-5 "
        >
          <label htmlFor="match-up-select">Match Up</label>
          <select
            required
            value={matchUp}
            onChange={(e) => setMatchUp(e.target.value)}
            name="match-up-select"
            id="match-up-select"
            className="text-black"
          >
            <option value="zvt">ZvT</option>
            <option value="zvp">ZvP</option>
            <option value="zvz">ZvZ</option>
            <option value="pvt">PvT</option>
            <option value="pvp">PvP</option>
            <option value="pvz">PvZ</option>
            <option value="tvt">TvT</option>
            <option value="tvz">TvZ</option>
            <option value="tvp">TvP</option>
          </select>
          <textarea
            required
            className="p-2 text-black"
            value={build}
            onChange={(e) => setBuildOrder(e.target.value)}
          ></textarea>
          <button type="submit" className="bg-white p-2 text-black">
            Submit
          </button>
        </form>
      </main>
    </>
  );
};

export default SubmitBuildPage;
